# Generated by Django 5.1.14 on 2025-12-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationevent',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
